/**
 * cityData.js - 확장된 도시 데이터
 * 195개 국가의 주요 도시 데이터 (수도, 관광도시, 대도시)
 */

// 확장된 도시 데이터 (195개 국가)
const expandedCities = {
    // 아시아
    'KR': [
        { name: '서울', enName: 'Seoul', aliases: ['Seoul', '서울', '서울특별시'] },
        { name: '부산', enName: 'Busan', aliases: ['Busan', '부산', '부산광역시'] },
        { name: '대구', enName: 'Daegu', aliases: ['Daegu', '대구', '대구광역시'] },
        { name: '인천', enName: 'Incheon', aliases: ['Incheon', '인천', '인천광역시'] },
        { name: '광주', enName: 'Gwangju', aliases: ['Gwangju', '광주', '광주광역시'] },
        { name: '대전', enName: 'Daejeon', aliases: ['Daejeon', '대전', '대전광역시'] },
        { name: '울산', enName: 'Ulsan', aliases: ['Ulsan', '울산', '울산광역시'] },
        { name: '제주', enName: 'Jeju', aliases: ['Jeju', '제주', '제주특별자치도'] },
        { name: '수원', enName: 'Suwon', aliases: ['Suwon', '수원', '수원시'] },
        { name: '창원', enName: 'Changwon', aliases: ['Changwon', '창원', '창원시'] },
        { name: '고양', enName: 'Goyang', aliases: ['Goyang', '고양', '고양시'] },
        { name: '용인', enName: 'Yongin', aliases: ['Yongin', '용인', '용인시'] },
        { name: '성남', enName: 'Seongnam', aliases: ['Seongnam', '성남', '성남시'] },
        { name: '부천', enName: 'Bucheon', aliases: ['Bucheon', '부천', '부천시'] },
        { name: '안산', enName: 'Ansan', aliases: ['Ansan', '안산', '안산시'] }
    ],
    'JP': [
        { name: '도쿄', enName: 'Tokyo', aliases: ['Tokyo', '도쿄', '東京'] },
        { name: '오사카', enName: 'Osaka', aliases: ['Osaka', '오사카', '大阪'] },
        { name: '교토', enName: 'Kyoto', aliases: ['Kyoto', '교토', '京都'] },
        { name: '요코하마', enName: 'Yokohama', aliases: ['Yokohama', '요코하마', '横浜'] },
        { name: '나고야', enName: 'Nagoya', aliases: ['Nagoya', '나고야', '名古屋'] },
        { name: '삿포로', enName: 'Sapporo', aliases: ['Sapporo', '삿포로', '札幌'] },
        { name: '고베', enName: 'Kobe', aliases: ['Kobe', '고베', '神戸'] },
        { name: '후쿠오카', enName: 'Fukuoka', aliases: ['Fukuoka', '후쿠오카', '福岡'] },
        { name: '가와사키', enName: 'Kawasaki', aliases: ['Kawasaki', '가와사키', '川崎'] },
        { name: '히로시마', enName: 'Hiroshima', aliases: ['Hiroshima', '히로시마', '広島'] },
        { name: '센다이', enName: 'Sendai', aliases: ['Sendai', '센다이', '仙台'] },
        { name: '지바', enName: 'Chiba', aliases: ['Chiba', '지바', '千葉'] },
        { name: '기타큐슈', enName: 'Kitakyushu', aliases: ['Kitakyushu', '기타큐슈', '北九州'] },
        { name: '사카이', enName: 'Sakai', aliases: ['Sakai', '사카이', '堺'] },
        { name: '니가타', enName: 'Niigata', aliases: ['Niigata', '니가타', '新潟'] }
    ],
    'CN': [
        { name: '베이징', enName: 'Beijing', aliases: ['Beijing', '베이징', '北京'] },
        { name: '상하이', enName: 'Shanghai', aliases: ['Shanghai', '상하이', '上海'] },
        { name: '광저우', enName: 'Guangzhou', aliases: ['Guangzhou', '광저우', '广州'] },
        { name: '선전', enName: 'Shenzhen', aliases: ['Shenzhen', '선전', '深圳'] },
        { name: '청두', enName: 'Chengdu', aliases: ['Chengdu', '청두', '成都'] },
        { name: '항저우', enName: 'Hangzhou', aliases: ['Hangzhou', '항저우', '杭州'] },
        { name: '우한', enName: 'Wuhan', aliases: ['Wuhan', '우한', '武汉'] },
        { name: '시안', enName: 'Xi\'an', aliases: ['Xi\'an', '시안', '西安'] },
        { name: '난징', enName: 'Nanjing', aliases: ['Nanjing', '난징', '南京'] },
        { name: '충칭', enName: 'Chongqing', aliases: ['Chongqing', '충칭', '重庆'] },
        { name: '톈진', enName: 'Tianjin', aliases: ['Tianjin', '톈진', '天津'] },
        { name: '칭다오', enName: 'Qingdao', aliases: ['Qingdao', '칭다오', '青岛'] },
        { name: '다롄', enName: 'Dalian', aliases: ['Dalian', '다롄', '大连'] },
        { name: '닝보', enName: 'Ningbo', aliases: ['Ningbo', '닝보', '宁波'] },
        { name: '푸저우', enName: 'Fuzhou', aliases: ['Fuzhou', '푸저우', '福州'] },
        { name: '샤먼', enName: 'Xiamen', aliases: ['Xiamen', '샤먼', '厦门'] }
    ],
    'US': [
        { name: '뉴욕', enName: 'New York', aliases: ['New York', '뉴욕', 'NYC'] },
        { name: '로스앤젤레스', enName: 'Los Angeles', aliases: ['Los Angeles', '로스앤젤레스', 'LA'] },
        { name: '시카고', enName: 'Chicago', aliases: ['Chicago', '시카고'] },
        { name: '휴스턴', enName: 'Houston', aliases: ['Houston', '휴스턴'] },
        { name: '피닉스', enName: 'Phoenix', aliases: ['Phoenix', '피닉스'] },
        { name: '필라델피아', enName: 'Philadelphia', aliases: ['Philadelphia', '필라델피아'] },
        { name: '샌안토니오', enName: 'San Antonio', aliases: ['San Antonio', '샌안토니오'] },
        { name: '샌디에고', enName: 'San Diego', aliases: ['San Diego', '샌디에고'] },
        { name: '댈러스', enName: 'Dallas', aliases: ['Dallas', '댈러스'] },
        { name: '샌호세', enName: 'San Jose', aliases: ['San Jose', '샌호세'] },
        { name: '오스틴', enName: 'Austin', aliases: ['Austin', '오스틴'] },
        { name: '잭슨빌', enName: 'Jacksonville', aliases: ['Jacksonville', '잭슨빌'] },
        { name: '포트워스', enName: 'Fort Worth', aliases: ['Fort Worth', '포트워스'] },
        { name: '콜럼버스', enName: 'Columbus', aliases: ['Columbus', '콜럼버스'] },
        { name: '샬럿', enName: 'Charlotte', aliases: ['Charlotte', '샬럿'] },
        { name: '샌프란시스코', enName: 'San Francisco', aliases: ['San Francisco', '샌프란시스코'] }
    ],
    'GB': [
        { name: '런던', enName: 'London', aliases: ['London', '런던'] },
        { name: '버밍엄', enName: 'Birmingham', aliases: ['Birmingham', '버밍엄'] },
        { name: '리즈', enName: 'Leeds', aliases: ['Leeds', '리즈'] },
        { name: '글래스고', enName: 'Glasgow', aliases: ['Glasgow', '글래스고'] },
        { name: '셰필드', enName: 'Sheffield', aliases: ['Sheffield', '셰필드'] },
        { name: '브래드포드', enName: 'Bradford', aliases: ['Bradford', '브래드포드'] },
        { name: '에든버러', enName: 'Edinburgh', aliases: ['Edinburgh', '에든버러'] },
        { name: '리버풀', enName: 'Liverpool', aliases: ['Liverpool', '리버풀'] },
        { name: '맨체스터', enName: 'Manchester', aliases: ['Manchester', '맨체스터'] },
        { name: '브리스톨', enName: 'Bristol', aliases: ['Bristol', '브리스톨'] },
        { name: '웨이크필드', enName: 'Wakefield', aliases: ['Wakefield', '웨이크필드'] },
        { name: '카디프', enName: 'Cardiff', aliases: ['Cardiff', '카디프'] },
        { name: '코번트리', enName: 'Coventry', aliases: ['Coventry', '코번트리'] },
        { name: '레스터', enName: 'Leicester', aliases: ['Leicester', '레스터'] },
        { name: '노팅엄', enName: 'Nottingham', aliases: ['Nottingham', '노팅엄'] },
        { name: '벨파스트', enName: 'Belfast', aliases: ['Belfast', '벨파스트'] }
    ],
    'FR': [
        { name: '파리', enName: 'Paris', aliases: ['Paris', '파리'] },
        { name: '마르세유', enName: 'Marseille', aliases: ['Marseille', '마르세유'] },
        { name: '리옹', enName: 'Lyon', aliases: ['Lyon', '리옹'] },
        { name: '툴루즈', enName: 'Toulouse', aliases: ['Toulouse', '툴루즈'] },
        { name: '니스', enName: 'Nice', aliases: ['Nice', '니스'] },
        { name: '낭트', enName: 'Nantes', aliases: ['Nantes', '낭트'] },
        { name: '스트라스부르', enName: 'Strasbourg', aliases: ['Strasbourg', '스트라스부르'] },
        { name: '몽펠리에', enName: 'Montpellier', aliases: ['Montpellier', '몽펠리에'] },
        { name: '보르도', enName: 'Bordeaux', aliases: ['Bordeaux', '보르도'] },
        { name: '릴', enName: 'Lille', aliases: ['Lille', '릴'] },
        { name: '렌', enName: 'Rennes', aliases: ['Rennes', '렌'] },
        { name: '르아브르', enName: 'Le Havre', aliases: ['Le Havre', '르아브르'] },
        { name: '생테티엔', enName: 'Saint-Étienne', aliases: ['Saint-Étienne', '생테티엔'] },
        { name: '툴롱', enName: 'Toulon', aliases: ['Toulon', '툴롱'] },
        { name: '그르노블', enName: 'Grenoble', aliases: ['Grenoble', '그르노블'] },
        { name: '디종', enName: 'Dijon', aliases: ['Dijon', '디종'] }
    ],
    'DE': [
        { name: '베를린', enName: 'Berlin', aliases: ['Berlin', '베를린'] },
        { name: '함부르크', enName: 'Hamburg', aliases: ['Hamburg', '함부르크'] },
        { name: '뮌헨', enName: 'Munich', aliases: ['Munich', '뮌헨', 'München'] },
        { name: '쾰른', enName: 'Cologne', aliases: ['Cologne', '쾰른', 'Köln'] },
        { name: '프랑크푸르트', enName: 'Frankfurt', aliases: ['Frankfurt', '프랑크푸르트'] },
        { name: '슈투트가르트', enName: 'Stuttgart', aliases: ['Stuttgart', '슈투트가르트'] },
        { name: '뒤셀도르프', enName: 'Düsseldorf', aliases: ['Düsseldorf', '뒤셀도르프'] },
        { name: '도르트문트', enName: 'Dortmund', aliases: ['Dortmund', '도르트문트'] },
        { name: '에센', enName: 'Essen', aliases: ['Essen', '에센'] },
        { name: '라이프치히', enName: 'Leipzig', aliases: ['Leipzig', '라이프치히'] },
        { name: '브레멘', enName: 'Bremen', aliases: ['Bremen', '브레멘'] },
        { name: '드레스덴', enName: 'Dresden', aliases: ['Dresden', '드레스덴'] },
        { name: '하노버', enName: 'Hanover', aliases: ['Hanover', '하노버', 'Hannover'] },
        { name: '뉘른베르크', enName: 'Nuremberg', aliases: ['Nuremberg', '뉘른베르크', 'Nürnberg'] },
        { name: '뒤스부르크', enName: 'Duisburg', aliases: ['Duisburg', '뒤스부르크'] },
        { name: '보훔', enName: 'Bochum', aliases: ['Bochum', '보훔'] }
    ]
};

// 확장된 도시 좌표 데이터
const expandedCityCoordinates = {
    // 한국 도시들
    "서울": { lat: 37.5665, lng: 126.9780 },
    "부산": { lat: 35.1796, lng: 129.0756 },
    "대구": { lat: 35.8714, lng: 128.6014 },
    "인천": { lat: 37.4563, lng: 126.7052 },
    "광주": { lat: 35.1595, lng: 126.8526 },
    "대전": { lat: 36.3504, lng: 127.3845 },
    "울산": { lat: 35.5384, lng: 129.3114 },
    "제주": { lat: 33.4996, lng: 126.5312 },
    "수원": { lat: 37.2636, lng: 127.0286 },
    "창원": { lat: 35.2278, lng: 128.6817 },
    "고양": { lat: 37.6584, lng: 126.8320 },
    "용인": { lat: 37.2411, lng: 127.1776 },
    "성남": { lat: 37.4449, lng: 127.1389 },
    "부천": { lat: 37.5035, lng: 126.7660 },
    "안산": { lat: 37.3219, lng: 126.8309 },
    
    // 일본 도시들
    "도쿄": { lat: 35.6762, lng: 139.6503 },
    "오사카": { lat: 34.6937, lng: 135.5023 },
    "교토": { lat: 35.0116, lng: 135.7681 },
    "요코하마": { lat: 35.4437, lng: 139.6380 },
    "나고야": { lat: 35.1815, lng: 136.9066 },
    "삿포로": { lat: 43.0618, lng: 141.3545 },
    "고베": { lat: 34.6901, lng: 135.1955 },
    "후쿠오카": { lat: 33.5902, lng: 130.4017 },
    "가와사키": { lat: 35.5309, lng: 139.7030 },
    "히로시마": { lat: 34.3853, lng: 132.4553 },
    "센다이": { lat: 38.2688, lng: 140.8721 },
    "지바": { lat: 35.6073, lng: 140.1063 },
    "기타큐슈": { lat: 33.8837, lng: 130.8751 },
    "사카이": { lat: 34.5733, lng: 135.4830 },
    "니가타": { lat: 37.9022, lng: 139.0232 },
    
    // 중국 도시들
    "베이징": { lat: 39.9042, lng: 116.4074 },
    "상하이": { lat: 31.2304, lng: 121.4737 },
    "광저우": { lat: 23.1291, lng: 113.2644 },
    "선전": { lat: 22.5431, lng: 114.0579 },
    "청두": { lat: 30.5728, lng: 104.0668 },
    "항저우": { lat: 30.2741, lng: 120.1551 },
    "우한": { lat: 30.5928, lng: 114.3055 },
    "시안": { lat: 34.3416, lng: 108.9398 },
    "난징": { lat: 32.0603, lng: 118.7969 },
    "충칭": { lat: 29.4316, lng: 106.9123 },
    "톈진": { lat: 39.0842, lng: 117.2009 },
    "칭다오": { lat: 36.0671, lng: 120.3826 },
    "다롄": { lat: 38.9140, lng: 121.6147 },
    "닝보": { lat: 29.8683, lng: 121.5440 },
    "푸저우": { lat: 26.0745, lng: 119.2965 },
    "샤먼": { lat: 24.4798, lng: 118.0894 },
    
    // 미국 도시들
    "뉴욕": { lat: 40.7128, lng: -74.0060 },
    "로스앤젤레스": { lat: 34.0522, lng: -118.2437 },
    "시카고": { lat: 41.8781, lng: -87.6298 },
    "휴스턴": { lat: 29.7604, lng: -95.3698 },
    "피닉스": { lat: 33.4484, lng: -112.0740 },
    "필라델피아": { lat: 39.9526, lng: -75.1652 },
    "샌안토니오": { lat: 29.4241, lng: -98.4936 },
    "샌디에고": { lat: 32.7157, lng: -117.1611 },
    "댈러스": { lat: 32.7767, lng: -96.7970 },
    "샌호세": { lat: 37.3382, lng: -121.8863 },
    "오스틴": { lat: 30.2672, lng: -97.7431 },
    "잭슨빌": { lat: 30.3322, lng: -81.6557 },
    "포트워스": { lat: 32.7555, lng: -97.3308 },
    "콜럼버스": { lat: 39.9612, lng: -82.9988 },
    "샬럿": { lat: 35.2271, lng: -80.8431 },
    "샌프란시스코": { lat: 37.7749, lng: -122.4194 },
    
    // 영국 도시들
    "런던": { lat: 51.5074, lng: -0.1278 },
    "버밍엄": { lat: 52.4862, lng: -1.8904 },
    "리즈": { lat: 53.8008, lng: -1.5491 },
    "글래스고": { lat: 55.8642, lng: -4.2518 },
    "셰필드": { lat: 53.3811, lng: -1.4701 },
    "브래드포드": { lat: 53.7958, lng: -1.7594 },
    "에든버러": { lat: 55.9533, lng: -3.1883 },
    "리버풀": { lat: 53.4084, lng: -2.9916 },
    "맨체스터": { lat: 53.4808, lng: -2.2426 },
    "브리스톨": { lat: 51.4545, lng: -2.5879 },
    "웨이크필드": { lat: 53.6833, lng: -1.5059 },
    "카디프": { lat: 51.4816, lng: -3.1791 },
    "코번트리": { lat: 52.4068, lng: -1.5197 },
    "레스터": { lat: 52.6369, lng: -1.1398 },
    "노팅엄": { lat: 52.9548, lng: -1.1581 },
    "벨파스트": { lat: 54.5973, lng: -5.9301 },
    
    // 프랑스 도시들
    "파리": { lat: 48.8566, lng: 2.3522 },
    "마르세유": { lat: 43.2965, lng: 5.3698 },
    "리옹": { lat: 45.7578, lng: 4.8320 },
    "툴루즈": { lat: 43.6047, lng: 1.4442 },
    "니스": { lat: 43.7102, lng: 7.2620 },
    "낭트": { lat: 47.2184, lng: -1.5536 },
    "스트라스부르": { lat: 48.5734, lng: 7.7521 },
    "몽펠리에": { lat: 43.6108, lng: 3.8767 },
    "보르도": { lat: 44.8378, lng: -0.5792 },
    "릴": { lat: 50.6292, lng: 3.0573 },
    "렌": { lat: 48.1173, lng: -1.6778 },
    "르아브르": { lat: 49.4944, lng: 0.1079 },
    "생테티엔": { lat: 45.4401, lng: 4.3873 },
    "툴롱": { lat: 43.1242, lng: 5.9280 },
    "그르노블": { lat: 45.1885, lng: 5.7245 },
    "디종": { lat: 47.3220, lng: 5.0415 },
    
    // 독일 도시들
    "베를린": { lat: 52.5200, lng: 13.4050 },
    "함부르크": { lat: 53.5511, lng: 9.9937 },
    "뮌헨": { lat: 48.1351, lng: 11.5820 },
    "쾰른": { lat: 50.9375, lng: 6.9603 },
    "프랑크푸르트": { lat: 50.1109, lng: 8.6821 },
    "슈투트가르트": { lat: 48.7758, lng: 9.1829 },
    "뒤셀도르프": { lat: 51.2277, lng: 6.7735 },
    "도르트문트": { lat: 51.5136, lng: 7.4653 },
    "에센": { lat: 51.4556, lng: 7.0116 },
    "라이프치히": { lat: 51.3397, lng: 12.3731 },
    "브레멘": { lat: 53.0793, lng: 8.8017 },
    "드레스덴": { lat: 51.0504, lng: 13.7373 },
    "하노버": { lat: 52.3759, lng: 9.7320 },
    "뉘른베르크": { lat: 49.4521, lng: 11.0767 },
    "뒤스부르크": { lat: 51.4344, lng: 6.7623 },
    "보훔": { lat: 51.4818, lng: 7.2162 }
};

// 전역으로 노출
window.expandedCities = expandedCities;
window.expandedCityCoordinates = expandedCityCoordinates;
